"""
Master Theorem: Divide-and-Conquer Recurrence Relations

This self-contained study script covers:
- Divide-and-conquer algorithms
- Recurrence relations
- Asymptotic notation
- The structure T(n) = aT(n/b) + f(n)
- The three standard cases of the Master Theorem
- The extended boundary case involving logarithmic factors
- Regularity conditions
- Recursion-tree intuition
- Common algorithm examples
- Edge cases and situations where the Master Theorem does not apply
- Numerical recurrence simulations
- Automatic classification for common recurrence forms
- Validation and testing
- Performance and implementation considerations

The mathematical analysis is represented using Python where possible.
The code is intended to be executable as a standalone educational file.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from math import log, ceil
from typing import Callable, Optional


# =============================================================================
# SECTION 1: DIVIDE-AND-CONQUER FUNDAMENTALS
# =============================================================================

"""
A divide-and-conquer algorithm typically performs three conceptual steps:

1. Divide:
   Split a problem of size n into smaller subproblems.

2. Conquer:
   Solve the subproblems recursively.

3. Combine:
   Combine their solutions and perform work associated with the current level.

A common recurrence is:

    T(n) = aT(n / b) + f(n)

where:

    T(n)   = running time for an input of size n
    a      = number of recursive subproblems
    n / b  = approximate size of each subproblem
    b      = factor by which the problem size decreases
    f(n)   = work performed outside recursive calls

The base case is often:

    T(1) = Theta(1)

Examples:

Binary search:
    T(n) = T(n/2) + Theta(1)

Merge sort:
    T(n) = 2T(n/2) + Theta(n)

A hypothetical algorithm creating four subproblems:
    T(n) = 4T(n/2) + Theta(n)

The Master Theorem analyzes many recurrences of this form.
"""


# =============================================================================
# SECTION 2: ASYMPTOTIC NOTATION
# =============================================================================

"""
The Master Theorem compares growth rates asymptotically.

Big-O:

    f(n) = O(g(n))

means that f(n) eventually grows no faster than a constant multiple of g(n).

Big-Omega:

    f(n) = Omega(g(n))

means that f(n) eventually grows at least as fast as a constant multiple of g(n).

Big-Theta:

    f(n) = Theta(g(n))

means that f(n) and g(n) have the same asymptotic growth rate.

The Master Theorem's critical comparison value is:

    n^(log_b(a))

This represents the total amount of work that is structurally generated by
the recursive branching pattern.
"""


def logarithm_base(value: float, base: float) -> float:
    """
    Compute log_base(value).

    Python's math.log can compute logarithms using:

        log(value, base)

    but the change-of-base identity makes the calculation explicit:

        log_b(x) = log(x) / log(b)
    """
    if value <= 0:
        raise ValueError("The logarithm value must be positive.")
    if base <= 0 or base == 1:
        raise ValueError("The logarithm base must be positive and not equal to 1.")

    return log(value) / log(base)


def critical_exponent(a: float, b: float) -> float:
    """
    Return log_b(a), the critical exponent used by the Master Theorem.

    For:

        T(n) = aT(n/b) + f(n)

    the critical comparison function is:

        n^(log_b(a))
    """
    if a < 1:
        raise ValueError("a must be at least 1 for standard divide-and-conquer recurrences.")
    if b <= 1:
        raise ValueError("b must be greater than 1.")

    return logarithm_base(a, b)


# =============================================================================
# SECTION 3: UNDERSTANDING n^(log_b(a))
# =============================================================================

"""
Consider:

    T(n) = aT(n/b) + f(n)

After one recursive level:
    a subproblems exist.

After two recursive levels:
    a^2 subproblems exist.

After k levels:
    a^k subproblems exist.

The recursion reaches constant-sized problems when:

    n / b^k = 1

Therefore:

    b^k = n

and:

    k = log_b(n)

The number of leaves is approximately:

    a^(log_b(n))

Using logarithmic identities:

    a^(log_b(n)) = n^(log_b(a))

Therefore n^(log_b(a)) is closely connected to the total number of
leaf-level subproblems.
"""


def recursion_depth(n: int, b: int) -> int:
    """
    Estimate the number of recursive levels required for n to reach 1.

    The recurrence model assumes repeated division by b.
    """
    if n < 1:
        raise ValueError("n must be at least 1.")
    if b <= 1:
        raise ValueError("b must be greater than 1.")

    depth = 0
    size = n

    while size > 1:
        size = ceil(size / b)
        depth += 1

    return depth


def leaf_count_estimate(n: int, a: int, b: int) -> float:
    """
    Estimate the number of recursion-tree leaves.

    This uses:

        a^(log_b(n))

    which is asymptotically equal to:

        n^(log_b(a))
    """
    if n < 1:
        raise ValueError("n must be positive.")
    if a < 1 or b <= 1:
        raise ValueError("Require a >= 1 and b > 1.")

    return a ** logarithm_base(n, b)


# =============================================================================
# SECTION 4: STANDARD MASTER THEOREM
# =============================================================================

"""
The standard recurrence is:

    T(n) = aT(n/b) + f(n)

with:

    a >= 1
    b > 1

Define:

    c = log_b(a)

The comparison function is:

    n^c

The three classical cases are based on comparing f(n) with n^c.

CASE 1: RECURSIVE WORK DOMINATES

If:

    f(n) = O(n^(c - epsilon))

for some epsilon > 0, then:

    T(n) = Theta(n^c)

Interpretation:
    The work produced by recursive branching dominates the non-recursive work.

CASE 2: BALANCED WORK

If:

    f(n) = Theta(n^c)

then:

    T(n) = Theta(n^c log n)

Interpretation:
    Each recursion level contributes approximately the same asymptotic work.

CASE 3: NON-RECURSIVE WORK DOMINATES

If:

    f(n) = Omega(n^(c + epsilon))

for some epsilon > 0, and the regularity condition holds:

    a f(n/b) <= c' f(n)

for some constant c' < 1 and sufficiently large n, then:

    T(n) = Theta(f(n))

Interpretation:
    The work performed outside recursive calls dominates the total complexity.
"""


# =============================================================================
# SECTION 5: REPRESENTING COMMON ASYMPTOTIC FUNCTIONS
# =============================================================================

@dataclass(frozen=True)
class PowerLogFunction:
    """
    Represents:

        f(n) = n^power * (log n)^log_power

    This representation handles many recurrence functions.

    Examples:

        Theta(1)
            power = 0, log_power = 0

        Theta(n)
            power = 1, log_power = 0

        Theta(n^2)
            power = 2, log_power = 0

        Theta(log n)
            power = 0, log_power = 1

        Theta(n log n)
            power = 1, log_power = 1

        Theta(n^2 log^3 n)
            power = 2, log_power = 3

    The exact logarithm base does not affect asymptotic classification when
    the base is a fixed constant greater than 1.
    """

    power: float
    log_power: float = 0.0

    def evaluate(self, n: float) -> float:
        """
        Numerically evaluate the represented function.

        log(max(n, 2)) avoids log(1) = 0 causing undefined behavior for
        negative logarithmic exponents in numerical demonstrations.
        """
        if n <= 0:
            raise ValueError("n must be positive.")

        safe_log = log(max(n, 2))
        return (n ** self.power) * (safe_log ** self.log_power)

    def describe(self) -> str:
        """Return a human-readable asymptotic description."""
        if self.power == 0 and self.log_power == 0:
            return "Theta(1)"

        parts = []

        if self.power != 0:
            if self.power == 1:
                parts.append("n")
            else:
                parts.append(f"n^{self.power:g}")

        if self.log_power != 0:
            if self.log_power == 1:
                parts.append("log n")
            else:
                parts.append(f"(log n)^{self.log_power:g}")

        return "Theta(" + " ".join(parts) + ")"


# =============================================================================
# SECTION 6: AUTOMATIC CLASSIFICATION FOR POWER FUNCTIONS
# =============================================================================

@dataclass
class MasterTheoremResult:
    """
    Stores the classification of a recurrence.

    This implementation focuses on recurrences whose non-recursive work can
    be represented as:

        n^p (log n)^k

    Such forms cover many important algorithms and also demonstrate the
    generalized boundary behavior.
    """

    case_name: str
    critical_exponent: float
    recurrence_work: str
    non_recursive_work: str
    result: str
    explanation: str


def classify_power_log_recurrence(
    a: float,
    b: float,
    f: PowerLogFunction,
    tolerance: float = 1e-10,
) -> MasterTheoremResult:
    """
    Classify common recurrences of the form:

        T(n) = aT(n/b) + n^p (log n)^k

    The primary comparison is between p and:

        log_b(a)

    If p differs from the critical exponent, the standard Case 1 or Case 3
    comparison applies.

    If p equals the critical exponent, logarithmic factors determine the
    boundary behavior.

    Generalized boundary rule:

        T(n) = aT(n/b) + Theta(n^c log^k n)

    where c = log_b(a), and k >= 0:

        T(n) = Theta(n^c log^(k+1) n)

    The standard Case 2 corresponds to k = 0.

    For k < 0, the ordinary Master Theorem is not sufficient in its simplest
    textbook form. More advanced recurrence techniques may be required.
    """
    c = critical_exponent(a, b)

    if f.power < c - tolerance:
        return MasterTheoremResult(
            case_name="Case 1: Recursive work dominates",
            critical_exponent=c,
            recurrence_work=f"The recursive structure contributes Theta(n^{c:g}).",
            non_recursive_work=f.describe(),
            result=f"Theta(n^{c:g})",
            explanation=(
                "The polynomial exponent of f(n) is smaller than log_b(a), "
                "so the recursive subproblems dominate asymptotically."
            ),
        )

    if f.power > c + tolerance:
        return MasterTheoremResult(
            case_name="Case 3 candidate: Non-recursive work dominates",
            critical_exponent=c,
            recurrence_work=f"The recursive structure contributes Theta(n^{c:g}).",
            non_recursive_work=f.describe(),
            result=f"Theta({format_power_log(f)})",
            explanation=(
                "The polynomial exponent of f(n) is larger than log_b(a). "
                "Under the required regularity condition, f(n) dominates."
            ),
        )

    if f.log_power == 0:
        return MasterTheoremResult(
            case_name="Case 2: Balanced work",
            critical_exponent=c,
            recurrence_work=f"Theta(n^{c:g})",
            non_recursive_work=f.describe(),
            result=f"Theta(n^{c:g} log n)",
            explanation=(
                "The non-recursive work matches the critical polynomial "
                "growth rate, so each recursion level has comparable work."
            ),
        )

    if f.log_power > 0:
        return MasterTheoremResult(
            case_name="Generalized balanced logarithmic case",
            critical_exponent=c,
            recurrence_work=f"Theta(n^{c:g})",
            non_recursive_work=f.describe(),
            result=f"Theta(n^{c:g} (log n)^{f.log_power + 1:g})",
            explanation=(
                "The polynomial part matches the critical exponent and the "
                "existing logarithmic factor gains one additional power."
            ),
        )

    return MasterTheoremResult(
        case_name="Boundary case requiring additional analysis",
        critical_exponent=c,
        recurrence_work=f"Theta(n^{c:g})",
        non_recursive_work=f.describe(),
        result="Not classified by the simple three-case implementation",
        explanation=(
            "The polynomial exponents match, but f(n) contains a negative "
            "logarithmic power. This is a boundary form that may require "
            "Akra-Bazzi, recursion-tree summation, substitution, or another "
            "advanced technique."
        ),
    )


def format_power_log(f: PowerLogFunction) -> str:
    """
    Format the mathematical expression without the Theta wrapper.
    """
    if f.power == 0 and f.log_power == 0:
        return "1"

    components = []

    if f.power != 0:
        if f.power == 1:
            components.append("n")
        else:
            components.append(f"n^{f.power:g}")

    if f.log_power != 0:
        if f.log_power == 1:
            components.append("log n")
        else:
            components.append(f"(log n)^{f.log_power:g}")

    return " ".join(components)


# =============================================================================
# SECTION 7: CLASSICAL EXAMPLE - BINARY SEARCH
# =============================================================================

"""
Binary search repeatedly discards approximately half of a sorted search space.

Recurrence:

    T(n) = T(n/2) + Theta(1)

Parameters:

    a = 1
    b = 2
    f(n) = 1

Critical exponent:

    log_2(1) = 0

Therefore:

    n^(log_2(1)) = n^0 = 1

The non-recursive work matches the critical function.

Case 2:

    T(n) = Theta(log n)
"""


def binary_search(sorted_values: list[int], target: int) -> int:
    """
    Iterative binary search.

    This implementation is included to connect the recurrence analysis with
    an actual algorithm.

    Time complexity:
        Theta(log n)

    Space complexity:
        Theta(1)
    """
    left = 0
    right = len(sorted_values) - 1

    while left <= right:
        middle = left + (right - left) // 2
        current = sorted_values[middle]

        if current == target:
            return middle

        if current < target:
            left = middle + 1
        else:
            right = middle - 1

    return -1


def recursive_binary_search(
    sorted_values: list[int],
    target: int,
    left: int = 0,
    right: Optional[int] = None,
) -> int:
    """
    Recursive binary search.

    The recursive call works on approximately half the previous range.

    A recursive implementation uses Theta(log n) call-stack space in the
    worst case.
    """
    if right is None:
        right = len(sorted_values) - 1

    if left > right:
        return -1

    middle = left + (right - left) // 2

    if sorted_values[middle] == target:
        return middle

    if sorted_values[middle] < target:
        return recursive_binary_search(
            sorted_values,
            target,
            middle + 1,
            right,
        )

    return recursive_binary_search(
        sorted_values,
        target,
        left,
        middle - 1,
    )


# =============================================================================
# SECTION 8: CLASSICAL EXAMPLE - MERGE SORT
# =============================================================================

"""
Merge sort divides an array into two halves, recursively sorts both halves,
and merges them.

Recurrence:

    T(n) = 2T(n/2) + Theta(n)

Parameters:

    a = 2
    b = 2
    f(n) = n

Critical exponent:

    log_2(2) = 1

Therefore:

    n^(log_2(2)) = n

Because f(n) = Theta(n), this is Case 2:

    T(n) = Theta(n log n)
"""


def merge(left_values: list[int], right_values: list[int]) -> list[int]:
    """
    Merge two sorted lists.

    Time complexity:
        Theta(len(left_values) + len(right_values))
    """
    merged: list[int] = []
    left_index = 0
    right_index = 0

    while left_index < len(left_values) and right_index < len(right_values):
        if left_values[left_index] <= right_values[right_index]:
            merged.append(left_values[left_index])
            left_index += 1
        else:
            merged.append(right_values[right_index])
            right_index += 1

    merged.extend(left_values[left_index:])
    merged.extend(right_values[right_index:])

    return merged


def merge_sort(values: list[int]) -> list[int]:
    """
    Recursive merge sort.

    Time complexity:
        Theta(n log n)

    Auxiliary space:
        Theta(n) for merging, depending on implementation details.
    """
    if len(values) <= 1:
        return values.copy()

    middle = len(values) // 2

    left_half = merge_sort(values[:middle])
    right_half = merge_sort(values[middle:])

    return merge(left_half, right_half)


# =============================================================================
# SECTION 9: CASE 1 EXAMPLE
# =============================================================================

"""
Consider:

    T(n) = 4T(n/2) + Theta(n)

Parameters:

    a = 4
    b = 2

Critical exponent:

    log_2(4) = 2

The critical comparison function is:

    n^2

But:

    f(n) = n

Since n grows polynomially slower than n^2:

    T(n) = Theta(n^2)

This is Case 1.
"""


def case_one_example() -> MasterTheoremResult:
    return classify_power_log_recurrence(
        a=4,
        b=2,
        f=PowerLogFunction(power=1),
    )


# =============================================================================
# SECTION 10: CASE 3 EXAMPLE
# =============================================================================

"""
Consider:

    T(n) = 2T(n/2) + Theta(n^2)

Parameters:

    a = 2
    b = 2

Critical exponent:

    log_2(2) = 1

The critical function is:

    n

The non-recursive work is:

    n^2

Since n^2 grows polynomially faster than n, Case 3 is a candidate.

The regularity condition must also hold:

    a f(n/b) <= c f(n)

For f(n) = n^2:

    2 * (n/2)^2
    = 2 * n^2/4
    = n^2/2

Thus:

    2f(n/2) <= (1/2)f(n)

with c = 1/2 < 1.

Therefore:

    T(n) = Theta(n^2)
"""


def case_three_example() -> MasterTheoremResult:
    return classify_power_log_recurrence(
        a=2,
        b=2,
        f=PowerLogFunction(power=2),
    )


# =============================================================================
# SECTION 11: EXTENDED CASE 2 WITH LOGARITHMIC FACTORS
# =============================================================================

"""
A commonly used extension handles:

    T(n) = aT(n/b) + Theta(n^c log^k n)

where:

    c = log_b(a)
    k >= 0

The result is:

    T(n) = Theta(n^c log^(k+1) n)

Example:

    T(n) = 2T(n/2) + n log n

Here:

    a = 2
    b = 2
    c = 1

The non-recursive work is:

    n log n = n^c log^1 n

Therefore:

    T(n) = Theta(n log^2 n)
"""


def generalized_case_two_example() -> MasterTheoremResult:
    return classify_power_log_recurrence(
        a=2,
        b=2,
        f=PowerLogFunction(power=1, log_power=1),
    )


# =============================================================================
# SECTION 12: RECURSION TREE ANALYSIS
# =============================================================================

@dataclass
class RecursionLevel:
    """
    Represents one recursion-tree level.
    """

    level: int
    number_of_subproblems: float
    size_per_subproblem: float
    work_per_subproblem: float
    total_level_work: float


def build_recursion_tree(
    n: int,
    a: int,
    b: int,
    f: Callable[[float], float],
) -> list[RecursionLevel]:
    """
    Build a numerical recursion-tree representation.

    At level i:

        number of subproblems = a^i
        size of each subproblem = n / b^i

    Therefore:

        total work at level i = a^i * f(n / b^i)

    The tree stops when subproblem size reaches approximately 1.

    This numerical model is useful for observing why different Master Theorem
    cases arise.
    """
    if n < 1:
        raise ValueError("n must be at least 1.")
    if a < 1:
        raise ValueError("a must be at least 1.")
    if b <= 1:
        raise ValueError("b must be greater than 1.")

    levels: list[RecursionLevel] = []
    level = 0
    current_size = float(n)

    while current_size > 1:
        subproblem_count = float(a ** level)
        work_per_subproblem = f(current_size)
        total_work = subproblem_count * work_per_subproblem

        levels.append(
            RecursionLevel(
                level=level,
                number_of_subproblems=subproblem_count,
                size_per_subproblem=current_size,
                work_per_subproblem=work_per_subproblem,
                total_level_work=total_work,
            )
        )

        current_size /= b
        level += 1

    return levels


def print_recursion_tree(levels: list[RecursionLevel]) -> None:
    """
    Print a compact recursion-tree table.
    """
    print(
        f"{'Level':<8}"
        f"{'Subproblems':<15}"
        f"{'Size Each':<15}"
        f"{'Work Each':<15}"
        f"{'Total Level Work':<20}"
    )

    for node in levels:
        print(
            f"{node.level:<8}"
            f"{node.number_of_subproblems:<15.2f}"
            f"{node.size_per_subproblem:<15.2f}"
            f"{node.work_per_subproblem:<15.2f}"
            f"{node.total_level_work:<20.2f}"
        )


# =============================================================================
# SECTION 13: OBSERVING LEVEL-WORK PATTERNS
# =============================================================================

"""
For Case 1:

    T(n) = 4T(n/2) + n

At level i:

    number of nodes = 4^i
    problem size = n/2^i
    work per node = n/2^i

Total level work:

    4^i * n/2^i
    = n * 2^i

The work increases toward the leaves.

For Case 2:

    T(n) = 2T(n/2) + n

At level i:

    number of nodes = 2^i
    work per node = n/2^i

Total level work:

    2^i * n/2^i
    = n

Every level performs Theta(n) work.

There are Theta(log n) levels.

Total:

    Theta(n log n)

For Case 3:

    T(n) = 2T(n/2) + n^2

At level i:

    total level work decreases geometrically:

        2^i * (n/2^i)^2
        = n^2 / 2^i

The root-level work dominates.

Total:

    Theta(n^2)
"""


# =============================================================================
# SECTION 14: NUMERICAL RECURRENCE SOLVER
# =============================================================================

def solve_recurrence_numerically(
    n: int,
    a: int,
    b: int,
    f: Callable[[int], float],
    base_cost: float = 1.0,
) -> float:
    """
    Numerically evaluate a recurrence:

        T(n) = aT(ceil(n/b)) + f(n)

    using memoization.

    Important distinction:
    The Master Theorem is asymptotic, while this function computes a concrete
    numerical recurrence for finite input sizes.

    Ceiling division handles input sizes that are not exact powers of b.
    """
    if n < 1:
        raise ValueError("n must be at least 1.")
    if a < 1:
        raise ValueError("a must be at least 1.")
    if b <= 1:
        raise ValueError("b must be greater than 1.")

    @lru_cache(maxsize=None)
    def recurrence(size: int) -> float:
        if size <= 1:
            return base_cost

        smaller_size = ceil(size / b)

        # Defensive guard against an invalid recursive reduction.
        if smaller_size >= size:
            raise RuntimeError("Recursive size did not decrease.")

        return a * recurrence(smaller_size) + f(size)

    return recurrence(n)


# =============================================================================
# SECTION 15: EMPIRICAL GROWTH COMPARISON
# =============================================================================

def compare_growth(
    recurrence_function: Callable[[int], float],
    theoretical_function: Callable[[int], float],
    input_sizes: list[int],
) -> list[tuple[int, float, float, float]]:
    """
    Compare a numerical recurrence with a theoretical asymptotic expression.

    The ratio:

        recurrence(n) / theoretical(n)

    does not need to converge to exactly 1.

    For Theta-equivalent functions, the ratio should generally remain bounded
    above and below by positive constants for sufficiently large n.
    """
    results = []

    for n in input_sizes:
        measured = recurrence_function(n)
        theoretical = theoretical_function(n)

        if theoretical == 0:
            ratio = float("inf")
        else:
            ratio = measured / theoretical

        results.append((n, measured, theoretical, ratio))

    return results


def print_growth_comparison(
    comparisons: list[tuple[int, float, float, float]]
) -> None:
    """
    Print recurrence and theoretical values.
    """
    print(
        f"{'n':<10}"
        f"{'Recurrence':<20}"
        f"{'Theory':<20}"
        f"{'Ratio':<15}"
    )

    for n, measured, theoretical, ratio in comparisons:
        print(
            f"{n:<10}"
            f"{measured:<20.4f}"
            f"{theoretical:<20.4f}"
            f"{ratio:<15.4f}"
        )


# =============================================================================
# SECTION 16: REGULARITY CONDITION
# =============================================================================

def check_regular_condition(
    a: float,
    b: float,
    f: Callable[[float], float],
    sample_sizes: list[int],
) -> list[tuple[int, float]]:
    """
    Numerically inspect the ratio:

        a f(n/b) / f(n)

    The Case 3 regularity condition requires that for sufficiently large n:

        a f(n/b) <= c f(n)

    for some constant c < 1.

    Therefore, if the sampled ratio remains below a value strictly smaller
    than 1 for large n, that supports the condition.

    This numerical function is not a mathematical proof. It is a diagnostic
    aid for understanding the condition.
    """
    if a < 1:
        raise ValueError("a must be at least 1.")
    if b <= 1:
        raise ValueError("b must be greater than 1.")

    ratios: list[tuple[int, float]] = []

    for n in sample_sizes:
        if n <= 1:
            continue

        numerator = a * f(n / b)
        denominator = f(n)

        if denominator == 0:
            ratio = float("inf")
        else:
            ratio = numerator / denominator

        ratios.append((n, ratio))

    return ratios


# =============================================================================
# SECTION 17: COMMON ALGORITHMS AND THEIR RECURRENCES
# =============================================================================

"""
1. Binary Search

    T(n) = T(n/2) + Theta(1)

    a = 1
    b = 2
    log_2(1) = 0

    Result:
        Theta(log n)


2. Merge Sort

    T(n) = 2T(n/2) + Theta(n)

    a = 2
    b = 2
    log_2(2) = 1

    Result:
        Theta(n log n)


3. Hypothetical Four-Way Recursive Algorithm

    T(n) = 4T(n/2) + Theta(n)

    a = 4
    b = 2
    log_2(4) = 2

    Result:
        Theta(n^2)


4. Matrix-Multiplication Style Recurrence

    T(n) = 8T(n/2) + Theta(n^2)

    a = 8
    b = 2
    log_2(8) = 3

    Result:
        Theta(n^3)


5. Strassen-Style Branching Pattern

    T(n) = 7T(n/2) + Theta(n^2)

    a = 7
    b = 2
    log_2(7) approximately equals 2.807

    Because n^2 is polynomially smaller than n^2.807:

        Theta(n^log_2(7))


6. Large Combine Step

    T(n) = 2T(n/2) + Theta(n^2)

    Result:
        Theta(n^2)
"""


# =============================================================================
# SECTION 18: STRASSEN-LIKE EXPONENT DEMONSTRATION
# =============================================================================

def strassen_style_exponent() -> float:
    """
    Compute log_2(7).

    The result is approximately 2.807, demonstrating how reducing the number
    of recursive subproblems can improve asymptotic complexity.
    """
    return critical_exponent(7, 2)


# =============================================================================
# SECTION 19: RECURRENCES THAT THE SIMPLE MASTER THEOREM DOES NOT HANDLE
# =============================================================================

"""
The standard Master Theorem does not apply directly to every recurrence.

EXAMPLE 1: Unequal subproblem sizes

    T(n) = T(n/3) + T(2n/3) + n

The recursive subproblems are not all the same size n/b.

The standard theorem requires a uniform subproblem size.

Possible approaches:
    - Recursion tree
    - Substitution
    - Akra-Bazzi theorem


EXAMPLE 2: Nonstandard reduction

    T(n) = T(n - 1) + n

The problem size decreases by subtraction rather than division.

This is not of the form n/b.

Expanding:

    T(n)
    = T(n-1) + n
    = T(n-2) + (n-1) + n
    = ...

The result is Theta(n^2).


EXAMPLE 3: Different subproblem counts

    T(n) = nT(n/2) + n

Here the number of recursive subproblems depends on n.

The standard theorem assumes constant a.


EXAMPLE 4: Problem-size-dependent division

    T(n) = 2T(n/log n) + n

The reduction factor is not a fixed constant b.


EXAMPLE 5: Oscillating or irregular f(n)

The regularity and polynomial separation assumptions can fail.

A recurrence may require direct expansion, bounding, or a more general theorem.
"""


# =============================================================================
# SECTION 20: UNEQUAL-SPLIT EXAMPLE
# =============================================================================

def unequal_split_cost(
    n: int,
    base_cost: float = 1.0,
) -> float:
    """
    Numerically evaluate:

        T(n) = T(floor(n/3)) + T(ceil(2n/3)) + n

    This is intentionally included as a recurrence that does NOT fit the
    simple Master Theorem.

    A guard ensures recursive sizes eventually decrease.
    """
    @lru_cache(maxsize=None)
    def recurrence(size: int) -> float:
        if size <= 1:
            return base_cost

        left_size = max(1, size // 3)
        right_size = max(1, (2 * size + 2) // 3)

        if right_size >= size:
            # For very small sizes, stop rather than create a non-decreasing call.
            return float(size)

        return (
            recurrence(left_size)
            + recurrence(right_size)
            + size
        )

    if n < 1:
        raise ValueError("n must be positive.")

    return recurrence(n)


# =============================================================================
# SECTION 21: SUBSTITUTION METHOD
# =============================================================================

"""
The substitution method solves a recurrence by:

1. Guessing an asymptotic bound.
2. Assuming the bound holds for smaller values.
3. Substituting that assumption into the recurrence.
4. Proving the resulting inequality.

Example:

    T(n) = 2T(n/2) + n

Guess:

    T(n) = O(n log n)

Assume:

    T(n/2) <= c(n/2)log(n/2)

Then:

    T(n)
    <= 2[c(n/2)log(n/2)] + n

    = cn(log n - 1) + n

    = cn log n - cn + n

For sufficiently large c, this can be bounded by:

    cn log n

A complete proof also needs base-case handling.

The substitution method is flexible and can solve many recurrences that are
not convenient for direct Master Theorem classification.
"""


# =============================================================================
# SECTION 22: ITERATION / EXPANSION METHOD
# =============================================================================

def expansion_terms_for_subtractive_recurrence(n: int) -> list[int]:
    """
    Return the non-recursive work terms for:

        T(n) = T(n-1) + n

    Expanding produces:

        n + (n-1) + ... + 2

    The sum is Theta(n^2).
    """
    if n < 1:
        raise ValueError("n must be positive.")

    return list(range(n, 1, -1))


def subtractive_recurrence_closed_form(n: int, base_cost: int = 1) -> int:
    """
    Compute the exact recurrence:

        T(1) = base_cost
        T(n) = T(n-1) + n

    The sum of integers gives:

        T(n) = base_cost + sum(k for k=2..n)

             = base_cost + n(n+1)/2 - 1

    This is Theta(n^2).
    """
    if n < 1:
        raise ValueError("n must be positive.")

    return base_cost + n * (n + 1) // 2 - 1


# =============================================================================
# SECTION 23: FLOOR AND CEILING ISSUES
# =============================================================================

"""
Real recursive algorithms often use:

    floor(n/b)
    ceil(n/b)

instead of exactly n/b.

Examples:

    T(n) = 2T(floor(n/2)) + n

or:

    T(n) = 2T(ceil(n/2)) + n

For many standard algorithms, floors and ceilings do not change the final
asymptotic result.

Nevertheless, implementation details matter:

- The recursive argument must decrease.
- Small values may behave differently from the idealized recurrence.
- Base cases must cover all terminating input sizes.
"""


def merge_sort_non_power_of_two_demo(values: list[int]) -> list[int]:
    """
    Demonstrates that merge sort works for sizes that are not powers of two.

    The recurrence is not literally identical at every branch because floor
    and ceiling-sized halves may occur, yet the asymptotic complexity remains
    Theta(n log n).
    """
    return merge_sort(values)


# =============================================================================
# SECTION 24: COMMON MISTAKES
# =============================================================================

"""
COMMON MISTAKE 1:
Comparing f(n) with a instead of n^(log_b(a)).

Incorrect:
    "There are 2 subproblems, so compare f(n) with 2."

Correct:
    Compute:

        n^(log_b(a))


COMMON MISTAKE 2:
Forgetting that b is the division factor.

For:

    T(n) = 8T(n/2) + n^2

the critical exponent is:

    log_2(8) = 3

not log_8(2).


COMMON MISTAKE 3:
Treating every larger f(n) as Case 3.

Case 3 requires polynomial separation in the standard theorem and a
regularity condition.

Boundary functions can require more careful analysis.


COMMON MISTAKE 4:
Ignoring logarithmic factors when polynomial exponents are equal.

For:

    T(n) = 2T(n/2) + n log n

f(n) is not simply identical to n.

The generalized logarithmic boundary rule yields:

    Theta(n log^2 n)


COMMON MISTAKE 5:
Applying the theorem to unequal subproblem sizes.

The recurrence:

    T(n) = T(n/3) + T(2n/3) + n

does not match aT(n/b).


COMMON MISTAKE 6:
Ignoring base cases.

A recurrence is incomplete without termination conditions.


COMMON MISTAKE 7:
Confusing exact runtime with asymptotic runtime.

The Master Theorem provides asymptotic growth, not an exact operation count.
"""


# =============================================================================
# SECTION 25: DECISION PROCEDURE
# =============================================================================

def master_theorem_decision_procedure(
    a: float,
    b: float,
    f: PowerLogFunction,
) -> MasterTheoremResult:
    """
    Apply a structured decision process.

    Step 1:
        Verify a >= 1 and b > 1.

    Step 2:
        Compute c = log_b(a).

    Step 3:
        Compare the polynomial exponent of f(n) with c.

    Step 4:
        If f(n) is polynomially smaller:
            Case 1.

    Step 5:
        If the polynomial exponents match:
            Case 2 or a logarithmic boundary extension.

    Step 6:
        If f(n) is polynomially larger:
            Case 3 candidate.

    Step 7:
        Verify the regularity condition when required.
    """
    return classify_power_log_recurrence(a, b, f)


# =============================================================================
# SECTION 26: ALGORITHM COMPLEXITY CATALOG
# =============================================================================

def algorithm_complexity_catalog() -> dict[str, MasterTheoremResult]:
    """
    Return several representative Master Theorem analyses.
    """
    return {
        "Binary search": classify_power_log_recurrence(
            1,
            2,
            PowerLogFunction(0),
        ),
        "Merge sort": classify_power_log_recurrence(
            2,
            2,
            PowerLogFunction(1),
        ),
        "Four-way recursion": classify_power_log_recurrence(
            4,
            2,
            PowerLogFunction(1),
        ),
        "Eight-way matrix-style recursion": classify_power_log_recurrence(
            8,
            2,
            PowerLogFunction(2),
        ),
        "Strassen-style recursion": classify_power_log_recurrence(
            7,
            2,
            PowerLogFunction(2),
        ),
        "Dominant combine step": classify_power_log_recurrence(
            2,
            2,
            PowerLogFunction(2),
        ),
        "Extended logarithmic boundary": classify_power_log_recurrence(
            2,
            2,
            PowerLogFunction(1, 1),
        ),
    }


# =============================================================================
# SECTION 27: PRACTICAL PERFORMANCE CONSIDERATIONS
# =============================================================================

"""
Asymptotic analysis is essential, but production performance depends on more
than the Master Theorem.

1. Constant factors

Theta(n log n) does not automatically mean one implementation is faster than
another Theta(n log n) implementation.

2. Memory allocation

Recursive algorithms may allocate temporary arrays or buffers.

3. Cache behavior

Memory-access patterns can strongly affect real performance.

4. Recursion overhead

Function calls and call-stack management have real costs.

5. Recursion depth

A theoretically logarithmic recursion depth is usually manageable, while
linear recursion can exceed language recursion limits.

6. Input distributions

Some algorithms have performance that depends on input structure.

7. Parallelism

Independent recursive subproblems can sometimes be processed concurrently,
although synchronization and communication introduce overhead.

8. Integer rounding

Actual subproblem sizes may differ by one because of floors and ceilings.

9. Base-case thresholds

Production implementations may stop recursion early and switch to a simpler
algorithm for small inputs.

Changing a constant-sized base threshold normally does not change the
asymptotic result, but it can significantly affect practical runtime.
"""


# =============================================================================
# SECTION 28: DEBUGGING RECURSIVE ALGORITHMS
# =============================================================================

def validate_recursive_problem_reduction(
    n: int,
    b: int,
) -> list[int]:
    """
    Return the sequence of sizes produced by repeated ceiling division.

    This can help detect a recursion that fails to make progress.
    """
    if n < 1:
        raise ValueError("n must be positive.")
    if b <= 1:
        raise ValueError("b must be greater than 1.")

    sizes = [n]
    current = n

    while current > 1:
        next_size = ceil(current / b)

        if next_size >= current:
            raise RuntimeError(
                "The recursive problem size is not decreasing."
            )

        sizes.append(next_size)
        current = next_size

    return sizes


def verify_merge_sort() -> None:
    """
    Basic correctness tests for merge sort.
    """
    test_cases = [
        [],
        [1],
        [2, 1],
        [3, 1, 2],
        [5, 4, 3, 2, 1],
        [1, 1, 1],
        [3, -1, 0, 3, 2],
    ]

    for values in test_cases:
        expected = sorted(values)
        actual = merge_sort(values)

        assert actual == expected, (
            f"Merge sort failed for {values}: "
            f"expected {expected}, got {actual}"
        )


def verify_binary_search() -> None:
    """
    Basic correctness tests for binary search.
    """
    values = [-10, -3, 0, 4, 9, 15]

    for index, target in enumerate(values):
        assert binary_search(values, target) == index
        assert recursive_binary_search(values, target) == index

    assert binary_search(values, 100) == -1
    assert recursive_binary_search(values, 100) == -1
    assert binary_search([], 5) == -1
    assert recursive_binary_search([], 5) == -1


def verify_master_theorem_examples() -> None:
    """
    Validate expected classifications for selected recurrence examples.
    """
    binary = classify_power_log_recurrence(
        1,
        2,
        PowerLogFunction(0),
    )
    assert "log n" in binary.result

    merge_result = classify_power_log_recurrence(
        2,
        2,
        PowerLogFunction(1),
    )
    assert "n^1 log n" in merge_result.result

    case_one = classify_power_log_recurrence(
        4,
        2,
        PowerLogFunction(1),
    )
    assert "n^2" in case_one.result

    case_three = classify_power_log_recurrence(
        2,
        2,
        PowerLogFunction(2),
    )
    assert "n^2" in case_three.result


# =============================================================================
# SECTION 29: PRINTING ANALYSIS RESULTS
# =============================================================================

def print_analysis(
    name: str,
    result: MasterTheoremResult,
) -> None:
    """
    Print a readable Master Theorem classification.
    """
    print(f"\n{name}")
    print("-" * len(name))
    print(f"Critical exponent log_b(a): {result.critical_exponent:.6f}")
    print(f"Recursive comparison:       {result.recurrence_work}")
    print(f"Non-recursive work:         {result.non_recursive_work}")
    print(f"Classification:             {result.case_name}")
    print(f"Result:                     {result.result}")
    print(f"Explanation:                {result.explanation}")


# =============================================================================
# SECTION 30: MAIN DEMONSTRATION
# =============================================================================

def main() -> None:
    """
    Execute demonstrations and validations.
    """
    print("=" * 72)
    print("MASTER THEOREM AND DIVIDE-AND-CONQUER RECURRENCE ANALYSIS")
    print("=" * 72)

    # -------------------------------------------------------------------------
    # Fundamental parameter demonstration
    # -------------------------------------------------------------------------

    print("\nFundamental calculations")

    a = 2
    b = 2

    exponent = critical_exponent(a, b)

    print(f"For a = {a}, b = {b}:")
    print(f"log_{b}({a}) = {exponent:.6f}")
    print(f"Therefore the critical function is Theta(n^{exponent:g}).")

    # -------------------------------------------------------------------------
    # Classical classifications
    # -------------------------------------------------------------------------

    print_analysis(
        "Binary Search: T(n) = T(n/2) + Theta(1)",
        classify_power_log_recurrence(
            1,
            2,
            PowerLogFunction(0),
        ),
    )

    print_analysis(
        "Merge Sort: T(n) = 2T(n/2) + Theta(n)",
        classify_power_log_recurrence(
            2,
            2,
            PowerLogFunction(1),
        ),
    )

    print_analysis(
        "Case 1 Example: T(n) = 4T(n/2) + Theta(n)",
        case_one_example(),
    )

    print_analysis(
        "Case 3 Example: T(n) = 2T(n/2) + Theta(n^2)",
        case_three_example(),
    )

    print_analysis(
        "Generalized Case: T(n) = 2T(n/2) + Theta(n log n)",
        generalized_case_two_example(),
    )

    # -------------------------------------------------------------------------
    # Algorithm correctness demonstrations
    # -------------------------------------------------------------------------

    print("\nAlgorithm demonstrations")

    search_values = [1, 3, 5, 7, 9, 11, 13]
    target = 9

    print(
        f"Binary search for {target} in {search_values}: "
        f"index {binary_search(search_values, target)}"
    )

    unsorted_values = [9, 3, 7, 1, 8, 2, 5]
    print(f"Merge sort input:  {unsorted_values}")
    print(f"Merge sort output: {merge_sort(unsorted_values)}")

    # -------------------------------------------------------------------------
    # Recursion tree demonstration
    # -------------------------------------------------------------------------

    print("\nRecursion tree for T(n) = 2T(n/2) + n, n = 16")

    merge_tree = build_recursion_tree(
        n=16,
        a=2,
        b=2,
        f=lambda size: size,
    )

    print_recursion_tree(merge_tree)

    # -------------------------------------------------------------------------
    # Numerical recurrence and theoretical comparison
    # -------------------------------------------------------------------------

    print("\nNumerical comparison for T(n) = 2T(n/2) + n")

    def merge_sort_recurrence(n: int) -> float:
        return solve_recurrence_numerically(
            n=n,
            a=2,
            b=2,
            f=lambda size: float(size),
        )

    input_sizes = [2, 4, 8, 16, 32, 64]

    comparisons = compare_growth(
        recurrence_function=merge_sort_recurrence,
        theoretical_function=lambda n: n * log(max(n, 2)),
        input_sizes=input_sizes,
    )

    print_growth_comparison(comparisons)

    # -------------------------------------------------------------------------
    # Case 3 regularity condition demonstration
    # -------------------------------------------------------------------------

    print("\nRegularity-condition ratios for f(n) = n^2")

    regularity_ratios = check_regular_condition(
        a=2,
        b=2,
        f=lambda size: size ** 2,
        sample_sizes=[4, 8, 16, 32, 64, 128],
    )

    for n, ratio in regularity_ratios:
        print(
            f"n = {n:<4} "
            f"a*f(n/b)/f(n) = {ratio:.4f}"
        )

    # -------------------------------------------------------------------------
    # Strassen-style exponent
    # -------------------------------------------------------------------------

    print("\nStrassen-style branching exponent")

    strassen_exponent = strassen_style_exponent()

    print(
        "For T(n) = 7T(n/2) + Theta(n^2): "
        f"log_2(7) = {strassen_exponent:.6f}"
    )
    print(
        "Because n^2 grows polynomially slower than "
        f"n^{strassen_exponent:.6f}, "
        "the recurrence is Theta(n^(log_2(7)))."
    )

    # -------------------------------------------------------------------------
    # Non-Master-Theorem recurrence
    # -------------------------------------------------------------------------

    print("\nSubtractive recurrence demonstration")

    for n in [1, 2, 5, 10]:
        value = subtractive_recurrence_closed_form(n)
        print(
            f"T({n}) for T(n) = T(n-1) + n is {value}"
        )

    # -------------------------------------------------------------------------
    # Recursive reduction validation
    # -------------------------------------------------------------------------

    print("\nRecursive size reduction for n = 37, b = 2")

    reduction_sequence = validate_recursive_problem_reduction(
        n=37,
        b=2,
    )

    print(" -> ".join(map(str, reduction_sequence)))

    # -------------------------------------------------------------------------
    # Automated correctness checks
    # -------------------------------------------------------------------------

    print("\nRunning validation tests")

    verify_merge_sort()
    verify_binary_search()
    verify_master_theorem_examples()

    print("All validation tests passed.")

    # -------------------------------------------------------------------------
    # Complexity catalog
    # -------------------------------------------------------------------------

    print("\nComplexity catalog")

    catalog = algorithm_complexity_catalog()

    for name, result in catalog.items():
        print(f"{name:<35} {result.result}")

    print("\nEnd of Master Theorem study script.")


if __name__ == "__main__":
    main()
